#!/bin/bash

# Divij Bhaw
# 23183845@student.uwa.edu.au
# Assignment 1 2022 class CITS2003
# TASK ONE

sortingVariable=$(tail incedenceOfMalaria.csv -n +2 | sort -k 1 -t, -n | sort -k 4 -t, -n | grep -w "$1" | tail -n1)
# Sort the CSV file , grep country or year and output Highest Rate row from file called incedenceOfMalaria.csv

country=$( echo $sortingVariable | cut -d, -f1)
year=$( echo $sortingVariable | cut -d, -f3)
rate=$( echo $sortingVariable | cut -d, -f4)
# set variables for country , year and rates

minYear=$(tail incedenceOfMalaria.csv -n +2 | cut -d, -f3 | sort | uniq | head -n1 )
MaxYear=$(tail incedenceOfMalaria.csv -n +2 | cut -d, -f3 | sort | uniq | tail -n1)
# find min a max year of the file

#if the statements to satisfy output conditions and outputs errors

if [[ $1 =~ ^[+-]?[0-9]+$ ]] &&  (($1 >= "$minYear" && $1 <= "$MaxYear"))
#check input is an interger and is between min and max year

then
    echo For the year $year, the country with the highest incidence was $country, with a rate of $rate per 1,000
    
elif [ "$country" == "$1" ]
#check if the input country is the same as the identified country

then
    echo For the country $country, the year with the highest incidence was $year, with a rate of $rate per 1,000
    
else
    echo "country or year not found in file or you have and invalid input "
    #catch any errors
fi


